- package-lock.json
- public/index.html
- src/components/Location/Map.tsx
- src/components/Location/index.tsx
- 상세페이지에 사용되는 Map.tsx 컴포넌트에 카카오맵 api 연동
- index.html에 카카오 sdk 추가하였습니다
- 브라우저 자동 번역 팝업 없애기 위해 `<html lang="ko">`로 바꿨습니다
> feat(17): 카카오맵 api 연동

- src/components/EventList/EventListItem.tsx
- src/components/EventMain/index.tsx
- src/components/TwitterInfo/index.tsx
- src/pages/Main.tsx
- src/styles/goodsInfoStyle.ts
- 특전 길이가 긴 경우 화면 깨짐 수정
- 트위터 계정명 앞에 `@` 추가
- 이벤트에 해시태그 없는 경우 표시되지 않도록 수정
- 메인 페이지 헤더에 `DateSelector` 컴포넌트 표시해뒀습니다
> fix(31): 특전 목록 스타일 수정, 계정명에 @ 추가, 해시태그 수정

- src/components/EventList/EventListItem.tsx
- src/components/EventMain/index.tsx
- src/components/EventsNearHere/EventNearHereLIst.tsx
- src/components/EventsNearHere/index.tsx
- src/components/TwitterInfo/index.tsx
- src/pages/Admin.tsx
- src/pages/Detail.tsx
- src/pages/Main.tsx
- src/styles/eventNearHereStyle.ts
- src/styles/goodsInfoStyle.ts
- 가까운 연관 이벤트 기능 구현
- 지역(ㅇㅇ시 ㅇㅇ구)와 아티스트 이름이 같은 경우로 필터링하였습니다
- 연관 이벤트가 없는 경우 상세페이지에 해당 컴포넌트 보이지 않도록 하였습니다
- 어드민 페이지에 이벤트 등록 완료 시 스크롤 상단으로 올라가도록 개선하였습니다
> feat(33): 가까운 연관 이벤트 구현

- package-lock.json
- src/apis/index.ts
- src/components/Filter/Bias.tsx
- src/components/Filter/BiasList.tsx
- src/components/header/DateSelector.tsx
- src/state/atoms.ts
- src/styles/filterStyle.ts
- src/types.ts
- supabase에 인물 테이블 `people` 생성
- recoil 전역 state 추가
- `monthState`: 메인페이지 상단 DateSelector로 선택한 월
- `biasState`: 메인페이지 상단 인물 프로필 클릭을 통해 선택한 연예인 이름
-  메인페이지 상단 인물 프로필 선택되지 않은 프로필은 `opacity: 0.5;` 적용하여 차이를 두었습니다 나중에 디자인 회의때 확인!!
- 인물 선택에 따른 메인페이지 이벤트리스트 필터링은 아직 하지않은 상태입니다!!! 
무한스크롤 버그부터 확인 후 적용하면 좋을 듯
> feat(20): 인물 테이블 생성 및 연동, recoil 전역 state 작성, 월별 생일 프로필 표시 구현

- src/components/GoodsInfo/index.tsx
- src/pages/Admin.tsx
- src/pages/Detail.tsx
- src/styles/goodsInfoStyle.ts
- src/types.ts
- supabase `detail` 테이블에 `tweetUrl` 컬럼 추가
- 어드민 페이지에 트윗 링크 입력 input 추가
- 상세페이지 `특전 자세히보기` 버튼 클릭 시 새창으로 열리도록 구현
- 기존에 입력된 데이터들에도 트윗링크 추가하였습니다.
- 어드민에서 데이터 입력 시에 `tweetUrl` 필수값입니다.
> feat(38): 특전 자세히보기 링크 추가

- src/components/EventList/index.tsx
- 무한 스크롤 시 중복 데이터만 연속으로 들어오는 버그 수정
- fetch 함수 리팩토링 하면서 pageParam이 전달되지 않게 되어 발생한 문제 🤹🏼‍♂️
> fix(26): 무한 스크롤 중복 데이터 버그 수정

- src/apis/index.ts
- src/pages/Detail.tsx
- 상세페이지에서 event 객체 불러지지 않는 버그 수정하였습니다
- api에 `fetchEventDetail` 함수 추가하여 상세페이지 진입 시 
두 테이블의 정보를 함께 가져오도록 처리하였습니다(`{ ...event, ...detail }`)
- api에 몇가지 주석 추가하였습니당
> fix(41): 상세페이지 데이터 fetch 버그 수정

- src/apis/index.ts
- src/components/EventList/index.tsx
- src/components/Filter/SearchInput.tsx
- src/state/atoms.ts
- src/types.ts
- supabase의 textSearch 메서드를 활용하여 검색창에 장소를 입력할 경우 결과가 렌더링되도록 구현함
- `민티베리`를 입력하면 카페 민티베리에서 열리는 이벤트가 검색 결과에 노출됩니다. 
- textSearch가 full text search에 쓰이는 메서드라 `민티`만 입력하면 검색 실패함... 그리고 `events` 테이블과 `detail` 테이블의 모든 컬럼에서 검색 결과를 가져오려면 결국 postgresql 문법으로 쿼리문을 짜는 방법밖에 없는 것으로 파악하였음 
- 나머지 작업은 시간이 더 걸릴 것 같아서 이슈는 close 하지 않고 구현한 부분만 올립니다~~
> feat(27) : 장소 full text search 구현 

- src/apis/index.ts
- src/types.ts
- events의 bias `["이름1", "이름2"]`에 맞춰 biasId `[13, 4]`입력되는 updateBiasIds 함수 추가
- people 테이블에 아직 입력되지 않은 아티스트 이름의 경우 `0`입력되도록 구현함
- supabase 상에서는 `["13", "4"]`로 보이나, 실제로 불러왔을 때 `[13, 4]`로 불러와짐!
> feat(72): updateBiasIds 함수 추가(event.biasId를 people.id와 연동)

- src/components/EventList/EventListItem.tsx
- src/components/EventMain/index.tsx
- src/shared/dateHandlers.ts
- src/styles/eventMainStyle.ts
- src/styles/layoutStyle.ts
- #60 
- 상세페이지 칩 노출 여러개 가능하도록 수정
- #61 
- `dateHandlers.ts`에 `convertDateWithDots`함수 추가(YYYYMMDD -> YYYY.MM.DD 형식으로 변환)
- #71 
- 날짜 필터 `width: 150px;` 고정
- 작은 스타일 이슈들 한번에 수정하였습니다~
> feat(60): 상세페이지 칩 노출 변경, 날짜 표기 변경, 메인 날짜필터 width 수정

- src/components/detail/styles/detailStyle.ts
- src/components/detail/styles/eventMainStyle.ts
- src/components/detail/styles/eventNearHereStyle.ts
- src/pages/Detail.tsx
가까운 연관 이벤트 가로 전체 너비 차지하도록 수정
- 상세 쪽 건드린 김에 이미지 `height: 100%`으로 수정만 해둠~ 하단 여백 남는 건 bug로 따로 이슈 생성할 예정 
- 데스크탑, 모바일 디자인 제플린으로 1080, 720, 480, 360px 장기적으로는 따로 다 만들어둬야겠단 생각이듦.!! 
- 포스터 세로 길이 `max-width`를 정해야 할 것 같음 
close #98
> feat(98): 가까운 연관 이벤트 가로 전체 너비 차지하도록 수정

- src/apis/index.ts
- src/components/detail/GoodsListItem.tsx
- src/components/request/ArtistInput.tsx
- src/components/request/Entry.tsx
- src/components/request/GoodsInput.tsx
- src/components/request/PosterUploader.tsx
- src/components/request/styles/requestStyle.ts
- src/shared/components/Button/index.tsx
- src/types.ts
- #122 
포스터 이미지 supabase storage에 입력 구현완료
- #124 
신청폼 데이터 events 테이블에 입력되도록 연동
- 신청 시 events 테이블에 아래와 같이 데이터 입력 됨! (나머지 place, organizer 등등의 값은 기존과 동일)
```
biasesId: null,
requestedBiases: [
{
"peopleId": 28,
"bias": "현재",
"team": "더보이즈"
},
{
"peopleId": 0,
"bias": "직접입력이름",
"team": "직접입력팀"
}
],
isRequested: true,
isApproved: false
```
| |isRequested|isApproved|
|------|---|---|
|신청받은데이터 | true | false |
|승인 | false | true | 
|승인거절 | false | false |
> feat(122): 신청 폼 supabase 연결 완료

- src/shared/components/layout/header/index.tsx
상세 페이지 뒤로가기 아이콘 추가
url /main 제외하고는 모두 뒤로가기 아이콘이 발생하도록 설정함(착각했으면 알랴조)
close #186
> fix(186): 상세 페이지 뒤로가기 아이콘 표시 

- src/components/detail/goodsItems/ExtraGoodsListItem.tsx
- src/components/detail/goodsItems/GoodsListItem.tsx
- src/components/detail/styles/detailStyle.ts
- src/components/detail/styles/eventNearHereStyle.ts
- src/components/detail/styles/goodsInfoStyle.ts
- src/components/detail/styles/twitterInfoStyle.ts
- src/components/request/styles/requestStyle.ts
- src/components/search/Result.tsx
- src/components/search/styles/eventStyle.ts
- src/pages/Request.tsx
- src/shared/components/BottomSheet/react-spring-bottom-sheet.css
- src/shared/components/GoodsChip/goodsChipStyle.ts
- src/shared/components/Icon/IconStyle.ts
- src/shared/components/layout/header/DateSelector.tsx
- src/shared/components/layout/header/headerStyle.ts
- src/shared/components/layout/header/index.tsx
- src/styles/gloabalStyle.ts
- #216 
- 상세페이지 스크롤바 삭제 그냥 전체 다 해둠! (body 태그에) 
480px제한된 화면에서 신청페이지 바텀시트가 중앙정렬이 안되는 문제 있어서 여기서도 스크롤바가 없어야되게 되어서 전체에서 제거해두었습니당
- 480px을 늦게 merge하면서 헤더가 좀 꼬인듯...!😢 달력 고치면서 다시 돌려뒀어용
예전으로 돌린 코드에 툴팁 부분만 복사해서 넣어놨는데 혹시 모르니까 확인 부탁드립니당
> fix(216): 1.0.0 수정

- src/components/search/Result.tsx
- src/components/search/SearchInput.tsx
- src/components/search/SearchModal.tsx
- src/components/search/types.ts
- src/pages/Search.tsx
- src/state/atoms.ts
- src/state/index.ts
검색 결과에서 상세보기 이동 후 돌아왔을 때 결과 리스트 유지되도록 수정
close #243
> feat(243): 검색 결과에서 상세보기 이동 후 돌아왔을 때 결과 리스트 유지되도록 수정

- src/components/main/BiasList.tsx
- src/components/main/EventList.tsx
- src/pages/Detail.tsx
- src/shared/components/Loading/index.tsx
- src/shared/components/Loading/loadingStyle.ts
- src/styles/gloabalStyle.ts
- src/styles/theme.ts
- #250 
- 메인, 상세페이지에 로딩스피너 추가함(현재 신청 페이지에는 로딩 필요없어서 안 넣음, 검색에는 필요하면 추가해주세요~!)
- scroll 다 smooth되는 이유가 reset에서 `html{ scroll-behavior: smooth }`를 해놔서 그랬음!!! 없앴어용
smooth 있는게 더 좋을 것 같은 페이지에는 따로 추가해서 사용하기!
> feat(250): 로딩스피너 추가(메인, 상세페이지), scroll-behavior 수정

- .gitignore
- src/components/detail/EventMain.tsx
- src/components/detail/EventNearHere.tsx
- src/components/detail/Location/index.tsx
- src/components/detail/TwitterInfo.tsx
- src/components/detail/styles/locationStyle.ts
- src/components/request/PreviewContent.tsx
- src/pages/Detail.tsx
- src/shared/components/Toast/toastStyle.ts
- src/shared/utils/copyHandlers.ts
- src/types.ts
- #254 
- #255 
- 지역명은 시/도 단위도 표현되도록 함 (예: `서울 마포구 연관 이벤트`)
> feat(254): 주소 복사 기능 추가, 가까운 연관 이벤트 명칭 변경

- src/components/search/Result.tsx
- src/components/search/styles/monthSelectorStyle.ts
- src/pages/Search.tsx
- src/shared/components/FilterIcon/filterIconStyle.ts
- src/shared/components/SortIcon/index.tsx
- src/shared/components/SortIcon/sortIconStyle.ts
- src/styles/theme.ts
- 현재 선택한 옵션 색 표시
- 정렬/필터 박스 default shadow 적용
- primary 컬러 opacity 50%적용해서 배경색 지정할 때 더 편하게 쓸 수 있도록 theme에 추가함 `theme.colors.softPrimary`
close #210
> feat(210): 검색 정렬/필터 UI 개선

- src/apis/index.ts
- src/apis/search/index.ts
- src/components/detail/EventMain.tsx
- src/components/detail/EventNearHere.tsx
- src/components/detail/GoodsInfo.tsx
- src/components/detail/Location/Map.tsx
- src/components/detail/Location/index.tsx
- src/components/detail/TwitterInfo.tsx
- src/components/main/EventListItem.tsx
- src/components/main/styles/mainStyle.ts
- src/components/request/Modals/DuplicatedModal.tsx
- src/components/request/Place/PlaceInput.tsx
- src/components/request/requestApi.ts
- src/components/request/requestType.ts
- src/components/search/Event.tsx
- src/pages/Detail.tsx
- src/pages/Request.tsx
- src/state/atoms.ts
- src/types.ts
1. 슈베에 temp_events 테이블 만들기 (이벤트 컬럼+디테일 컬럼, 그리고 newDistrict랑 districts 같이 있음)
1-1. temp_place_sort 뷰 만들기
2. 코드 temp_events, temp_place_sort 바라보도록 수정 (배포된 페이지는 원래 events, detail, place_sort 보고있으니까 오류 없음. 코드에 newDistrict 없도록 수정하기. detail 테이블 엮여있는거 다 수정.)
아직 완료되지 않아서 이슈 닫지 않습니다~~
> feat(268): temp_events로 테이블 이동

- components/detail/index.tsx
- shared/components/layout/header/index.tsx
상세 페이지 링크로 직접 진입 시 뒤로가기 메인으로 이동시키기 위해 `layout/index.tsx`에 작성했던 코드 제거 후 
`detail/index.tsx`에 `handleBackClick`함수를 추가하여 세션 스토리지에 저장된 검색 키워드가 없는 경우 메인으로 돌아가도록 수정함 
(사이드 이펙트로 인해 검색 > 상세 뒤로가기 시 메인으로 돌아가고 있었기 때문~~)
> hotfix: 검색 > 상세 뒤로가기 시 메인으로 돌아가는 문제 수정

- components/search/hooks/useBiasList.ts
- components/search/index.tsx
- shared/components/biasProfile/index.tsx
/search 페이지 인물 리스트 중 작년 이벤트만 있는 인물이 노출되어 로직 변경 
- 2~12월 사이의 이벤트는 올해 열린 이벤트만 유효한 것으로 여김
- 12~1월 사이의 이벤트는 작년, 올해 이벤트를 유효한 것으로 여김
> fix: search 작년 이벤트만 있는 인물 제거
