o-cup/o-cup-web

package-lock.json, package.json, public/index.html, src/components/EventList/EventListItem.tsx, src/components/EventList/index.tsx, src/components/Filter/Bias.tsx, src/components/Filter/BiasList.tsx, src/components/Filter/SearchInput.tsx, src/components/Filter/index.tsx, src/components/header/DateSelector.tsx, src/components/layout/Header.tsx, src/pages/Main.tsx, src/styles/eventListStyle.ts, src/styles/filterStyle.ts, src/styles/gloabalStyle.ts, src/styles/headerStyle.ts, src/styles/layoutStyle.ts
- Header, Content 퍼블리싱 완료
- react-icons 설치했어요
- 이미지는 우선 샘플로 url 따와서 올려놨습니당
- 경계가 잘 안 보여서 임시로 body에 background #000000 검정 처리 해뒀습니당 나중에 배포 전에 빼기!!
=> Feat(header): Header, Content 퍼블리싱 완료

package-lock.json, package.json, src/App.tsx
=> fix(7): react-helmet-async 설치하여 콘솔 경고 메시지 제거

.gitignore, package-lock.json, package.json, src/components/EventList/EventListItem.tsx, src/components/EventList/index.tsx, src/index.tsx, src/supabaseClient.js, src/types.ts
EventList에 supabse 데이터 연동
- firebase 해보다가 화나서 supabase 써봤는데 완전 쉬움!! 접속 정보는 디스코드로 공유~ 
- 상태 관리 라이브러리가 결국에는 필요해질 것 같음 
close #9
=> feat(9): EventList 컴포넌트에 supabase 데이터 연동

package-lock.json, src/App.tsx, src/apis/index.ts, src/pages/Admin.tsx, src/styles/adminStyle.ts
- 이벤트 입력 페이지 작성 및 supabase 연동
- 라우팅 `/admin` 으로 처리함
- 현재 따로 보안정책이 없기 때문에 누구나 `/admin` 접속 시 이벤트 등록 가능합니다! 논의 필요합니다
- 필수값 임의로 적용해두었습니다~ 다음 회의때 픽스합시닷
=> feat(29): 이벤트 입력 페이지 작성 및 supabase 연동

src/apis/index.ts, src/components/Filter/BiasList.tsx, src/pages/Detail.tsx, src/styles/adminStyle.ts, src/styles/eventListStyle.ts, src/styles/filterStyle.ts, src/styles/gloabalStyle.ts, src/styles/layoutStyle.ts, src/styles/theme.ts
- theme에 media query 내용 추가
- 데스크탑 환경의 경우 메인페이지 이벤트 2줄로 표시되도록 스타일 적용(추후 논의 후 수정!)
- 검색창 height 40px로 높혀두었습니당
- `720px`을 기준으로 모바일/데스크탑 구분하였습니다
- 최대넓이 `max-width: 1280px;`으로 적용해두었습니다~~~
=> feat(43): media query theme 추가, 데스크탑 스타일 세팅

src/styles/filterStyle.ts, src/styles/gloabalStyle.ts, src/styles/goodsInfoStyle.ts
이슈 #45 참고 ~~ 
- button에 color 지정하지 않았을 때 사파리 모바일웹에서 디폴트 색상으로 표시해버린 것이었음 
close #45
=> fix(45): 사파리 모바일 웹에서 아이콘 및 텍스트 하늘색으로 표시되는 버그 수정

src/styles/eventListStyle.ts, src/styles/filterStyle.ts
- 검색 input 높이 수정
- 데스크탑 이벤트 리스트 스타일 버그 수정
- `base: develop` 브랜치입니당
=> feat(48): 검색 input 높이 수정, 데스크탑 이벤트 리스트 스타일 버그 수정

src/styles/gloabalStyle.ts
=> fix(50): globalStyle 수정

src/components/EventList/EventListItem.tsx, src/components/Filter/BiasList.tsx, src/components/header/DateSelector.tsx, src/pages/Detail.tsx, src/shared/dateHandlers.ts, src/state/atoms.ts, src/styles/detailStyle.ts, src/styles/eventListStyle.ts, src/styles/layoutStyle.ts
- dateHandlers.ts 추가
- 메인페이지 날짜필터 단위 변경
- desktop max-width: 1080px로 변경
- desktop 메인페이지 리스트 4줄로 표현
- desktop 상세페이지 2줄로 표현
=> feat(54): 날짜 변환 dateHandlers.ts 추가, 회의 내용 반영

src/components/EventList/EventListItem.tsx, src/components/Filter/BiasList.tsx, src/components/header/DateSelector.tsx, src/pages/Detail.tsx, src/shared/dateHandlers.ts, src/state/atoms.ts, src/styles/detailStyle.ts, src/styles/eventListStyle.ts, src/styles/filterStyle.ts, src/styles/gloabalStyle.ts, src/styles/layoutStyle.ts
=> feat(develop): 데스크탑 레이아웃 디자인 변경

src/apis/index.ts
- 검색창에 키워드를 입력했을 때, events 테이블 전체 데이터를 쿼리하여 bias, place, organizer, district 컬럼이 키워드를 포함하면 필터링하여 리턴하는 방식으로 검색 구현함
- supabase 쿼리문을 작성하지 않고, 클라이언트에서 필터링해서 보여주는 방식으로 우선 구현하였습니다. 나중에 성능 문제가 생기면 개선을 검토해야 할듯 
close #27
=> feat(27): 인물, 장소, 주최자, 지역 데이터 필터링하여 검색 결과 노출

src/apis/index.ts, src/components/EventList/index.tsx, src/shared/dateHandlers.ts, src/types.ts
- 메인 리스트에 "오픈된 이벤트"만 노출되도록 구현
- 기존 `dateHandlers.ts`에 버그가 있어 수정하였습니다~
=> feat(64): 메인 리스트 날짜필터 적용

src/styles/layoutStyle.ts
Footer 아이콘 영역 `display: none` 처리
오픈 이후 재논의 
close #67
=> feat(67): Footer 아이콘 영역 숨김

src/components/EventList/EventListItem.tsx, src/components/EventMain/index.tsx, src/components/Filter/SearchInput.tsx, src/components/Filter/index.tsx, src/styles/eventListStyle.ts, src/styles/eventMainStyle.ts, src/styles/filterStyle.ts
- 모든 컴포넌트 아이콘 fontawesome으로 통일
- 아이콘 변경 후 크기 및 정렬 조금씩 조정하였습니다. 
- 변경하면서 #62 이슈 함께 처리함 
close #70 #62
=> feat(70): 아이콘 fontawesome으로 통일 

src/apis/index.ts
- supabase에 random_sort 스니펫 작성하여 이벤트 순서 랜덤으로 쿼리할 수 있도록 설정 후 코드에 반영 
- `SQL Editor > New query` 작성 후 이름 한 번 변경했는데, `Table Editor > All Views`에 변경 전 후 버전 두 개 다 뜨고 있음!! 이전 것이 사라지지 않음.. 없애고싶다 
close #58
=> feat(58): 이벤트 쿼리 랜덤 순서 적용 

src/components/EventList/index.tsx, src/components/Filter/Bias.tsx, src/components/Filter/BiasList.tsx, src/components/header/DateSelector.tsx, src/state/atoms.ts, src/types.ts
- #57 
- 인물 선택 biasFilterAtom 배열로 수정
- #79 
- 해당 날짜에 열려있는 이벤트 주인공만 메인페이지 상단에 표시되도록 수정
- 인물 클릭 시 하단 이벤트리스트 필터링 적용
=> feat(57, 79): 인물 필터 구현

src/apis/index.ts, src/components/EventList/EventListItem.tsx, src/components/EventList/index.tsx, src/components/EventMain/index.tsx, src/components/EventsNearHere/index.tsx, src/pages/Detail.tsx, src/shared/components/BiasChip/BiasChip.tsx, src/shared/components/BiasChip/BiasChipStyle.ts, src/styles/eventListStyle.ts, src/styles/eventMainStyle.ts, src/types.ts
- 컬럼 이름 `biasesId`로 변경, id로 쿼리하여 people 테이블에서 이름 가져도록 변경함
- `BiasChip.tsx` 공통 컴포넌트 작성 및 기존 스타일 이동
- 컴포넌트 구조가 너무 복잡해짐 ㅜㅜ!! 한번 정리해야겠다 
close #81
=> feat(81): 인물 id로 테이블 쿼리, 칩 공통 컴포넌트 작성

src/styles/eventMainStyle.ts
- 오타 있어서 스타일 적용 안되고 있었음!!! 수정했습니당
=> fix(84): eventMainStyle.ts 버그 수정

src/shared/components/layout/header/index.tsx
- header 달력 수정함
- 바로 merge할게요~
=> fix(111): header 컴포넌트 수정

src/apis/index.ts, src/components/detail/GoodsListItem.tsx, src/components/request/ArtistInput.tsx, src/components/request/Entry.tsx, src/components/request/GoodsInput.tsx, src/components/request/Modal.tsx, src/components/request/PosterUploader.tsx, src/components/request/styles/modalStyle.ts, src/components/request/styles/requestStyle.ts, src/shared/components/Button/index.tsx, src/types.ts
- 신청 폼 등록완료 시 팝업 추가하였습니다
- 추후 다른 페이지에서도 사용할 수 있도록 공용컴포넌트로 쓰면 좋을듯!
=> feat(126): 신청 폼 modal 추가

src/components/detail/GoodsListItem.tsx, src/components/detail/styles/detailStyle.ts, src/components/detail/styles/eventMainStyle.ts, src/components/detail/styles/eventNearHereStyle.ts, src/components/detail/styles/goodsInfoStyle.ts, src/components/detail/styles/locationStyle.ts, src/components/detail/styles/twitterInfoStyle.ts, src/components/main/styles/mainStyle.ts, src/components/request/ArtistInput.tsx, src/components/request/DateRangeInput.tsx, src/components/request/PosterUploader.tsx, src/components/request/styles/artistInputStyle.ts, src/components/request/styles/basicInputStyle.ts, src/components/request/styles/dateRangeInputStyle.ts, src/components/request/styles/goodsInputStyle.ts, src/components/request/styles/posterUploadStyle.ts, src/components/request/styles/request-calendar-custom.css, src/components/request/styles/requestStyle.ts, src/components/request/styles/searchInputStyle.ts, src/pages/Detail.tsx, src/shared/components/layout/styles/layoutStyle.ts
- #132 
- 상세 내용 이슈에 적어놨으니 확인해주세요~
- 신청 폼 전체 input 폰트사이즈 14px로 조정했습니다
- #116 
- `vertical-align : bottom;` 처리하면 되는거였음!!!!
- https://junistory.blogspot.com/2017/07/blog-post_25.html
=> fix(132): 디자인 수정사항 반영

src/components/detail/EventNearHere.tsx
=> fix(143): 연관이벤트 버그 수정

src/App.tsx, src/components/detail/GoodsInfo.tsx, src/components/detail/GoodsListItem.tsx, src/components/request/Artist/ArtistInput.tsx, src/components/request/Artist/ArtistInputContainer.tsx, src/components/request/DateRange/DateRangeInput.tsx, src/components/request/Entry.tsx, src/components/request/FcfsGoods/FcfsGoodsInput.tsx, src/components/request/Goods/GoodsInput.tsx, src/components/request/HashTags/HashTagsContainer.tsx, src/components/request/LuckyDraw/LuckyDrawInput.tsx, src/components/request/Place/PlaceInput.tsx, src/components/request/Poster/PosterUploader.tsx, src/components/request/PreviewContent.tsx, src/components/request/requestApi.ts, src/components/request/requestType.ts, src/pages/Admin.tsx, src/pages/Detail.tsx, src/pages/Request.tsx, src/state/atoms.ts, src/types.ts
- supabase `detail`의 `goods` 형식 변경하였습니다.
기존에 입력했던 데이터들은 직접입력(extra)로 넣어서 적용하였습니다~
- 예전 형식의 데이터는 우선 `prevGoods`로 옮겨둠! 나중에 컬럼 삭제하기!
- request atom 각각 따로 있던거 너무 많아져서 하나로 합쳤습니당
=> feat(157): 특전 형식 변경, request atom 정리

src/components/detail/GoodsInfo.tsx, src/components/detail/goodsItems/FcfsGoodsListItem.tsx, src/components/detail/goodsItems/LuckyGoodsListItem.tsx, src/components/detail/styles/goodsInfoStyle.ts, src/components/request/FcfsGoods/FcfsGoodsInput.tsx, src/components/request/PreviewContent.tsx, src/components/request/requestApi.ts, src/pages/Main.tsx
- 신청 폼 미리보기 수정
- Main.tsx에 세션 초기화 추가
- highlight width 고정
- 신청폼 세션 초기화하는 부분 
우선 Main 페이지에 들어가는 경우에 sessionStorage.clear() 하는 것으로 처리해뒀는데, 메인 아닌 다른 페이지로 이동하더라도 데이터 삭제되어야한다면 수정해야할듯!
=> feat(161): 신청 폼 미리보기 수정, Main.tsx에 세션 초기화 추가, highlight width 고정

src/shared/components/Icon/IconStyle.ts, src/shared/components/layout/header/headerStyle.ts
뒤로가기 커서 영역 정상화 
헤더 텍스트의 width가 영역을 침범해서 발생한 버그였음!! 
close #178
=> feat(178): 뒤로가기 커서 영역 정상화

src/components/search/Event.tsx, src/components/search/styles/eventStyle.ts
오늘 일자가 이벤트데이인 경우 초록색 컬러 표시 
- 임시데이터 만들어서 테스트했고 빨리 삭제해야되니깐 캡쳐로 확인부탁!!
close #182
=> feat(182): 이벤트데이 표시

src/apis/index.ts, src/apis/search/index.ts, src/components/search/Result.tsx, src/components/search/SearchInput.tsx, src/components/search/styles/searchStyle.ts, src/pages/Search.tsx, src/shared/components/BiasProfile/biasProfileStyle.ts, src/shared/components/BiasProfile/index.tsx
검색 페이지 인물 클릭 시 이벤트 렌더링
- 인물 클릭 시에는 다른 컬럼 조회하지 않고 biasId 매칭만 찾도록 처리
close #183
=> feat(183): 검색 페이지 인물 클릭 시 이벤트 렌더링

package-lock.json, src/components/detail/EventMain.tsx, src/components/detail/goodsItems/LuckyGoodsListItem.tsx, src/components/detail/styles/eventMainStyle.ts, src/components/detail/styles/goodsInfoStyle.ts, src/components/request/Artist/ArtistInput.tsx, src/components/request/DateRange/DateRangeInput.tsx, src/components/request/Entry.tsx, src/components/request/FcfsGoods/FcfsGoodsInput.tsx, src/components/request/FcfsGoods/fcfsGoodsInputStyle.ts, src/components/request/LuckyDraw/LuckyDrawInput.tsx, src/components/request/LuckyDraw/luckyInputStyle.ts, src/components/request/Modals/AlertModal.tsx, src/components/request/Modals/ConfirmModal.tsx, src/components/request/Modals/SubmitModal.tsx, src/components/request/Place/PlaceInput.tsx, src/components/request/Poster/posterUploadStyle.ts, src/components/request/PreviewContent.tsx, src/components/request/requestApi.ts, src/components/request/styles/requestStyle.ts, src/components/request/units/BasicInput.tsx, src/components/request/units/basicInputStyle.ts, src/pages/Detail.tsx, src/pages/Main.tsx, src/pages/Request.tsx, src/shared/components/Modal/index.tsx, src/shared/components/Modal/modalStyle.ts, src/types.ts
=> fix(189): 신청페이지, 상세페이지 버그 수정

src/components/request/Place/PlaceInput.tsx, src/components/request/requestApi.ts, src/components/request/requestType.ts, src/pages/Request.tsx, src/state/atoms.ts
- 카카오 api 사용하여 법정동코드(b_code) 추출
=> feat(191): 이벤트 장소등록 시 지역코드 입력 구현(newDistrict)

src/components/request/Place/PlaceInput.tsx
=> fix(202): 카카오 장소검색 수정

src/components/request/Place/PlaceInput.tsx, src/shared/components/layout/header/index.tsx
=> feat(develop): Update main branch

public/index.html, src/components/detail/EventNearHere.tsx, src/components/detail/styles/eventNearHereStyle.ts, src/components/main/BiasList.tsx, src/components/main/styles/mainStyle.ts, src/components/request/GoodsChipInput/goodsChipInputsStyle.ts, src/components/request/styles/requestStyle.ts, src/shared/components/GoodsChip/goodsChipStyle.ts, src/shared/components/Icon/IconStyle.ts, src/shared/components/layout/footer/index.tsx, src/shared/components/layout/header/DateSelector.tsx, src/shared/components/layout/header/HeaderCalendar/header-calendar-custom.css, src/shared/components/layout/header/HeaderCalendar/index.tsx, src/shared/components/layout/header/headerStyle.ts, src/shared/components/layout/header/index.tsx, src/shared/components/layout/styles/layoutStyle.ts
- #208 
- #197 
- #169 
- description "응원하는 아티스트의 생일 이벤트를 한눈에 확인해보세요!"으로 수정함
=> 디자인 수정사항 반영

src/pages/Search.tsx, src/shared/components/layout/header/index.tsx, src/shared/components/layout/index.tsx
검색 결과 화면에서 뒤로가기 시 검색 입력 페이지로 이동
- Header 컴포넌트에 handleBackClick 함수를 옵셔널로 넘길 수 있도록 수정함
close #211
=> feat(211): 검색 결과 화면에서 뒤로가기 시 검색 입력 페이지로 이동

public/index.html
=> hotfix(221): csp 설정 제거

.eslintrc.js, public/index.html, src/components/main/EventList.tsx, src/shared/components/GoogleAdvertise/index.tsx
- 구글 애드센스 구현중
- 로컬에서 테스트 불가하여 PR 올립니당
=> feat(229): 구글 애드센스 구현중

src/components/main/EventList.tsx
- `/main/EventList.tsx` 파일에 `<GoogleAdvertise/>` 컴포넌트 주석처리함!
=> feat(develop): 구글 애드센스 컴포넌트 숨김

src/components/request/LuckyDraw/LuckyDrawInput.tsx
- 신청페이지 "럭키드로우 없음" 최초에 선택되어있지 않도록 수정
=> fix(233): 신청페이지 럭키드로우 체크박스 수정

src/apis/search/index.ts, src/components/search/Event.tsx, src/components/search/Result.tsx, src/components/search/styles/eventStyle.ts, src/components/search/styles/resultStyle.ts, src/components/search/styles/searchStyle.ts, src/pages/Search.tsx, src/shared/components/FilterIcon/filterIconStyle.ts
=> feat(141): 검색 기능 복구

src/components/request/Artist/ArtistInput.tsx, src/components/search/styles/eventStyle.ts, src/types.ts
- #237 
- enName, koName, realName, team으로도 검색되도록 수정함!
=> feat(237): 신청페이지 아티스트검색 영어, 한글이름 검색 구현

src/apis/search/index.ts, src/components/search/DistrictSelector.tsx, src/components/search/Result.tsx, src/components/search/SearchModal.tsx, src/components/search/types.ts, src/hooks/useRegcodes.ts, src/pages/Search.tsx, src/state/atoms.ts, src/state/index.ts, src/types.ts
- `지역 전체` 선택 시 필터링 되지 않는 검색 로직 오류 수정
- 검색 키워드 변경 시 필터칩 초기화되도록 수정
=> feat(141): 검색 로직 오류 수정, 검색필터칩 키워드 변경 시 초기화 

src/components/main/BiasList.tsx, src/shared/components/layout/header/index.tsx
날짜 변경 시 생일자 최우선 재정렬되도록 수정
- useQuery 트리거에 선택 날짜 추가함 
close #241
=> fix(241): 날짜 변경 시 생일자 최우선 재정렬되도록 수정

src/components/search/Result.tsx, src/pages/Search.tsx, src/shared/components/layout/header/index.tsx
검색 결과 페이지에서 트위터 공유하기 구현 
close #141
=> feat(141): 검색 결과 페이지 트위터 공유하기 구현 

src/components/search/Result.tsx, src/components/search/SearchInput.tsx, src/pages/Search.tsx, src/shared/components/layout/header/index.tsx
- 검색 페이지 트위터 공유하기 아이콘 제거(인코딩 오류로 인함)
- 검색어 입력 후 지울 때마다 데이터 쿼리되는 문제 수정
=> fix(141): 인풋 입력 후 키보드로 삭제 시 데이터 쿼리되는 문제 수정

src/components/search/Result.tsx, src/pages/Search.tsx
검색 페이지 로딩 스피너 적용
- 로딩 스피너 사라진 이후에도 인물 사진이 순서대로 렌더링 되는 것 개선 필요함 
close #263
=> feat(263): 검색 페이지 로딩 스피너 적용

public/index.html, src/shared/utils/metaTagHandlers.ts
- 트위터 공유 시 카드에 이미지 표시되지 않는 문제 수정... (배포 후 확인 가능)
=> feat(269): 트위터 공유 이미지 경로 수정

public/index.html, src/shared/utils/metaTagHandlers.ts
=> fix(269): 이미지 변경

public/index.html, public/robots.txt, src/shared/utils/metaTagHandlers.ts
=> Update main branch 

src/pages/Search.tsx
=> fix(269): meta tag 수정중

src/components/search/Result.tsx
=> feat(275): 디폴트값 가나다순으로 변경

public/index.html
=> feat(292): 네이버 메타태그 추가

src/components/search/styles/searchInputStyle.ts
- input 폰트 사이즈 웹접근성에 맞추어 16px로 변경
close #296
=> feat(296): input font-size 16px로 변경

src/components/detail/EventMain.tsx, src/components/request/Modals/ConfirmModal.tsx, src/components/request/Place/PlaceInput.tsx, src/components/request/Poster/PosterUploader.tsx, src/components/request/Poster/posterUploadStyle.ts, src/components/request/PreviewContent.tsx, src/components/request/requestApi.ts, src/components/request/styles/requestStyle.ts, src/pages/Request.tsx, src/shared/components/BottomSheet/index.tsx, src/state/atoms.ts
=> feat(299): 포스터업로드 로직 변경, 미리보기 수정

src/apis/search/index.ts, src/components/search/Event.tsx, src/components/search/MonthSelector.tsx, src/components/search/Result.tsx, src/components/search/SearchInput.tsx, src/components/search/styles/searchInputStyle.ts, src/components/search/utils.ts, src/pages/Search.tsx, src/state/atoms.ts, src/state/index.ts, src/types.ts
- 검색 셀렉트박스 구현
- 검색 로직 변경 (영문 입력 시 대소문자 관계없이 검색되도록 수정)
- 폰트사이즈 16px으로 맞추어뒀는데 점검 필요... 데스크탑에선 부적절해보이나 현재로서는 최선임.. 
close #309
=> feat(309): 검색 셀렉트박스 구현

src/components/detail/TwitterInfo.tsx, src/components/detail/goodsItems/FcfsGoodsListItem.tsx, src/components/detail/goodsItems/GoodsListItem.tsx, src/components/detail/styles/goodsInfoStyle.ts, src/components/main/EventListItem.tsx, src/components/main/styles/mainStyle.ts, src/components/request/FcfsGoods/FcfsGoodsInput.tsx, src/components/request/Goods/GoodsSelectBox.tsx, src/components/request/GoodsChipInput/GoodsChipCountInput.tsx, src/components/request/GoodsChipInput/GoodsChipInput.tsx, src/components/request/Place/PlaceInput.tsx, src/components/request/units/searchInputStyle.ts, src/styles/gloabalStyle.ts
- 특전 이름 띄어쓰기, placeholder 수정
- 가이드 문구 수정
- 매일 -> 기념일 제외로 문구 수정
- 메인 "혼다 히토미" 줄바꿈 방지
=> feat(316): 가이드 문구, 특전 문구 띄어쓰기 등등 수정

src/apis/index.ts, src/apis/search/index.ts
- temp_events -> events
temp_place_sort -> place_sort
수정!
=> feat(268): temp 없는 테이블로 수정

src/components/main/Bias/BiasList.tsx, src/components/main/Bias/biasStyles.ts, src/components/request/CategoryInput/index.tsx, src/components/request/Entry.tsx, src/components/request/requestApi.ts, src/components/request/requestType.ts, src/components/request/styles/requestStyle.ts, src/pages/Request.tsx, src/shared/components/CategoryChip/categoryChipStyle.ts, src/shared/components/CategoryChip/index.tsx, src/shared/components/Toast/toastStyle.ts, src/state/atoms.ts, src/styles/theme.ts
=> feat(328): 신청폼 카테고리 추가

components/detail/Location/Map.tsx, components/main/index.tsx, components/request/DateRange/dateRangeInputStyle.ts, components/request/Place/PlaceInput.tsx, components/request/index.tsx, next.config.js, package-lock.json, package.json, pages/_app.tsx, shared/components/layout/header/headerCalendar/index.tsx, shared/components/layout/header/index.tsx, shared/components/layout/header/style.ts, shared/styles/gloabalStyle.ts
- `feat/next`로 머지합니당~!
- 캘린더 라이브러리 수정(`next-transpile-modules` 설치함)
- 카카오 window is not defined 에러 수정
- 카카오맵 js 동적추가 오류 있어서, 추후 develop 브랜치와 동일하게 정적추가로 변경 필요
=> feat(340): next 캘린더, 카카오맵 수정

.eslintrc.js, components/main/index.tsx, components/request/DateRange/DateRangeInput.tsx, components/request/DateRange/dateRangeInputStyle.ts, components/search/Result.tsx, components/search/SearchInput.tsx, components/search/index.tsx, components/search/styles/searchInputStyle.ts, pages/_app.tsx, pages/detail/[eid].tsx, pages/search.tsx, shared/components/calendar/calendarStyle.ts, shared/components/calendar/index.tsx, shared/components/layout/header/index.tsx, shared/hooks/index.ts, shared/hooks/useClearData.ts, shared/state/atoms.ts, shared/state/index.ts
- 검색 및 헤더 정상화 
여기까지 feat/next에 머지한 다음 전체 테스트 계속 하면서 메타 태그 부분 수정할 예정~~
=> feat(344): 검색 및 헤더 정상화 

public/index.html, src/components/detail/Location/Map.tsx, src/components/request/Place/PlaceInput.tsx, src/pages/Request.tsx
=> fix(develop): 카카오 에러 대응

public/index.html, src/pages/Request.tsx
=> fix(develop): 카카오 에러 대응 정상화

package-lock.json, package.json, pages/_app.tsx
=> feat(368): 구글 애널리틱스 연결

components/detail/index.tsx, components/search/styles/eventStyle.ts, pages/detail/[eid].tsx, pages/search.tsx, shared/apis/common.ts, shared/components/layout/index.tsx, shared/types/index.ts
- 상세페이지 조회수 기능 구현
- 한 사람이 여러번 클릭해도 조회수 계속 늘어나기 때문에 추후 어떻게 개선할지 생각해봐야할듯..!
=> feat(370): 상세페이지 조회수 구현

components/detail/index.tsx
=> feat(370): local 환경에서는 조회수 올라가지 않도록 수정

components/request/index.tsx, components/request/modals/SubmitModal.tsx, components/request/requestStyle.ts, shared/components/categoryChip/index.tsx, shared/styles/theme.ts
- 포토부스 중복검사 해제
- 카테고리 이름 변경(식당->음식점)
- 신청완료 모달 버튼 깨짐 수정, 문구 변경
=> feat(394): 신청 페이지 수정내용 반영

components/request/artist/ArtistInput.tsx, components/search/hooks/useAutoComplete.ts, components/search/index.tsx, components/search/styles/searchInputStyle.ts
=> feat(404): 아티스트 이름 정렬 수정

components/detail/DetailMainInfo.tsx, components/detail/EventNearHere.tsx, components/detail/GoodsInfo.tsx, components/detail/TwitterInfo.tsx, components/detail/styles/detailMainInfoStyle.ts, components/detail/styles/eventNearHereStyle.ts, components/detail/styles/goodsInfoStyle.ts, components/detail/styles/twitterInfoStyle.ts, components/main/EventListItem.tsx, components/request/FormPage.tsx, components/request/PreviewContent.tsx, components/request/modals/DuplicatedModal.tsx, components/request/requestApi.ts, components/request/requestStyle.ts, components/search/Event.tsx, components/search/styles/eventStyle.ts
- #402 
- 주최자 닉네임 표시되는 부분, 신청페이지 주최자 모두 삭제했습니다~
=> feat(402): 주최자 닉네임 생략

components/detail/TwitterInfo.tsx, components/detail/styles/twitterInfoStyle.ts, components/request/requestStyle.ts
- 중복 확인 페이지 간격 개선
- 공지 바로가기 버튼 색상 변경 등
- 사파리 placeholder 색상 문제는 별도의 이슈로 처리하겠습니다~~ ㅜㅜ 
#411
=> feat(411): 스타일 이슈 개선 

components/detail/styles/detailStyle.ts, components/request/PreviewContent.tsx
=> feat(develop): 미리보기 스타일 간격 개선 

shared/components/layout/header/index.tsx
=> Update main branch

components/main/EventListItem.tsx, components/search/Event.tsx, shared/components/layout/header/index.tsx, shared/components/layout/header/style.ts
next/link 사용 가능한 부분 변경 
next/link의 Link 사용하면 페이지를 리로드 하지 않고 spa처럼 동작합니다. 
close #421
=> feat(421): 라우팅 next/link로 변경 

components/main/EventSection.tsx, components/main/biasList/BiasList.tsx, pages/index.tsx
- 메인페이지 getServerSideProps를 사용하여 리액트 prefetch 기능으로 데이터 캐싱 구현 
close #424
=> feat(424): getServerSideProps에서 데이터 prefetch 구현

components/main/EmptyDefault.tsx, components/main/EventListItem.tsx, components/main/EventSection.tsx, next.config.js, pages/index.tsx
- 메인 포스터 이미지에 next/image 적용하여 lazy-loading 및 이미지 사이즈 최적화
- 메인 데이터 호출 getStaticProps로 변경
이어서 작업 예정
=> fix(427): lighthouse 분석 후 최적화

components/search/hooks/useAutoComplete.ts
- 영어 소문자로 검색했을때 대문자로 등록되어있는 아티스트 이름 검색되지 않는 문제 수정 
- 매칭되는 이름 찾는 공통 함수 작성 후 리팩토링 필요
=> hotfix(develop): 검색 자동완성 대소문자 구별하는 문제 수정

components/main/EventList.tsx, pages/_document.tsx, shared/components/KaKaoAdFit/index.tsx
- KakaoAdFit 컴포넌트 생성 
- shared/components 하위에 생성하였고, 원하는 컴포넌트 위치 내에서 import 하여 사용하면 됨 
- EventList 최상단에 위치시켜봄
=> feat(develop): 카카오 애드핏 위치 변경

components/main/EventList.tsx, components/main/EventSection.tsx, components/main/biasList/BiasList.tsx, components/main/fetchers.ts, components/main/index.tsx, pages/index.tsx, shared/apis/common.ts
- 메인 SSR 데이터 페치 구현
- 메인 최상단 biasList SSR 데이터 페치 적용
- 이벤트 리스트 개선 작업 중
=> refactor(460): 메인 데이터 페치 개선 

shared/components/KakaoAdFit/index.tsx
광고 영역 기본 높이 지정 (화면 흔들리는 현상 개선을 위함)
=> feat(460): 광고 영역 기본 높이 지정

.eslintrc.js, components/detail/DetailMainInfo.tsx, components/request/PreviewDetailMainInfo.tsx, pages/detail/[eid].tsx, shared/components/biasChip/biasChipStyle.ts, shared/components/biasChip/index.tsx, shared/utils/metaTags.ts
메인 데이터 페치 SSR 구현 및 캐싱 개선 
상세 > 메인으로 뒤로가기 시 속도 개선을 위함
=> refactor: 메인 데이터 페치 SSR 구현 및 캐싱 개선 

.prettierrc, components/request/requestApi.ts
- 제출 시 해시태그 마지막 언더스코어 제거
- github에서 인덴트 다르게 보이는 현상 수정 (useTabs)
=> 해시태그 마지막 언더스코어 제거, 인덴트 오차 수정 

components/request/CategoryChip.tsx, components/request/CheckPage.tsx, components/request/categoryInput/index.tsx, shared/components/categoryChip/index.tsx, shared/constants.ts
신청 페이지에서 새로고침 시 카테고리 초기화, 버튼 비활성화 되는 문제 수정
=> fix(develop): 신청 페이지 새로고침 시 버튼 비활성화 되는 문제 수정
